version: '2'

networks:
    browtest_network:

services:
    php:
        build: ./build/php
        container_name: browtest_php
        volumes:
            - ./code:/code
        ports:
            - "9900:9000"
        networks:
            - browtest_network
